development:
  # Configure available database clients. (required)
  clients:
    # Defines the default client. (required)
    default:
      uri: mongodb+srv://gemintangsfurqon:disvandal13@cluster0.ltpg2rs.mongodb.net/JTKBerbagi
      options:
        server_selection_timeout: 5

test:
  clients:
    default:
      database: backend_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
